#!/usr/bin/env bash
# Module: 09 — fstab Generation
# Handbook Reference: https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System#Creating_the_fstab_file

module_09_fstab() {
    show_chapter_header "Chapter 9" "Generating /etc/fstab" \
        "https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System#Creating_the_fstab_file"

    # ── Step 9.1 — generate fstab ────────────────────────────────────────────
    show_step 1 "Generate /etc/fstab from current mounts"
    show_tip "/etc/fstab tells the kernel which filesystems to mount at boot and where. Using UUIDs (instead of device names like /dev/sda1) is safer because UUIDs don't change even if you add or remove disks."

    run_or_type "blkid" \
        "Show block device UUIDs and filesystem types. We use these UUIDs when writing fstab." \
        "https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System#Creating_the_fstab_file"

    # Auto-generate fstab
    local root_part swap_part boot_part chosen_fs
    root_part=$(load_progress "ROOT_PART")
    swap_part=$(load_progress "SWAP_PART")
    boot_part=$(load_progress "BOOT_PART")
    chosen_fs=$(load_progress "CHOSEN_FS")
    chosen_fs="${chosen_fs:-ext4}"

    local root_uuid swap_uuid boot_uuid
    root_uuid=$(blkid -s UUID -o value "$root_part" 2>/dev/null || echo "FILL-IN-ROOT-UUID")
    if [[ -n "$swap_part" ]]; then
        swap_uuid=$(blkid -s UUID -o value "$swap_part" 2>/dev/null || echo "FILL-IN-SWAP-UUID")
    fi
    if [[ -n "$boot_part" ]]; then
        boot_uuid=$(blkid -s UUID -o value "$boot_part" 2>/dev/null || echo "FILL-IN-BOOT-UUID")
    fi

    local fstab_content
    fstab_content="# /etc/fstab — generated by gentoo-trainer
# <filesystem>               <mountpoint>  <type>   <options>         <dump>  <pass>
"
    if [[ -n "$boot_uuid" ]]; then
        fstab_content+="UUID=${boot_uuid}  /boot/efi     vfat     defaults,noatime  0       2
"
    fi
    fstab_content+="UUID=${root_uuid}  /             ${chosen_fs}  defaults,noatime  0       1
"
    if [[ -n "$swap_uuid" ]]; then
        fstab_content+="UUID=${swap_uuid}  none          swap     sw                0       0
"
    fi
    fstab_content+="proc                        /proc         proc     nosuid,noexec,nodev 0 0
"

    echo ""
    echo -e "  ${BOLD}Generated fstab:${RESET}"
    echo "─────────────────────────────────────────────────────────────────"
    echo "$fstab_content"
    echo "─────────────────────────────────────────────────────────────────"

    echo ""
    printf "  Write this fstab to /etc/fstab? [Y/n]: "
    local confirm
    read -r confirm
    if [[ "${confirm,,}" != "n" ]]; then
        echo "$fstab_content" > /etc/fstab
        log_success "fstab written to /etc/fstab."
    fi
    mark_step_complete "09.1"

    # ── Step 9.2 — review and edit ───────────────────────────────────────────
    show_step 2 "Review and edit /etc/fstab"
    show_tip "fstab fields are: filesystem, mount point, type, options, dump frequency, and fsck pass order. The root filesystem should have pass=1; all others should be 2 or 0."

    run_or_type "nano /etc/fstab" \
        "Open /etc/fstab in nano for review and any manual corrections. Ensure UUIDs match what blkid reported. Save with Ctrl+O and exit with Ctrl+X." \
        "https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System#Creating_the_fstab_file"
    mark_step_complete "09.2"

    log_success "Module 09 — fstab generation complete."
}
